name: Console Build & Tests

on:
  push:
    paths:
      - 'frontend/console/**'
      - '.github/workflows/console.yml'
  pull_request:
    paths:
      - 'frontend/console/**'
      - '.github/workflows/console.yml'

jobs:
  console:
    # Dieser Job ist deaktiviert, bis ein Lockfile in frontend/console/ vorhanden ist; aktiviert sich automatisch.
    if: ${{ hashFiles('frontend/console/package-lock.json', 'frontend/console/pnpm-lock.yaml', 'frontend/console/yarn.lock') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install
        working-directory: frontend/console
        run: npm ci
      - name: Lint
        working-directory: frontend/console
        run: npm run lint
      - name: Test
        working-directory: frontend/console
        run: npm test
      - name: Build
        working-directory: frontend/console
        env:
          VITE_API_BASE: 'http://localhost:8000'
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: console-dist
          path: frontend/console/dist
