---
name: Node CI (Guard)
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  build:
    if: ${{ hashFiles('**/package-lock.json', '**/yarn.lock') != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lockfile present – placeholder success
        run: echo "Lockfile found → Node job allowed; placeholder step only."
