---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Python CI (Focused Mahnwesen)

on:
  push:
    paths:
      - 'agents/**'
      - 'tools/**'
      - 'tests/agents_mahnwesen/**'
      - 'docs/agents/**'
      - '.github/workflows/python.yml'
      - '.vscode/tasks.json'
  pull_request:
    paths:
      - 'agents/**'
      - 'tools/**'
      - 'tests/agents_mahnwesen/**'
      - 'docs/agents/**'
      - '.github/workflows/python.yml'
      - '.vscode/tasks.json'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      TZ: UTC
      PYTHONHASHSEED: '0'
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: '1'
      RUN_DB_TESTS: '0'
      TENANT_DEFAULT: '00000000-0000-0000-0000-000000000001'
      MVR_KILL_SWITCH: '1'
      MVR_RATE_LIMIT: '2'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          else
            python -m pip install pytest pytest-cov httpx freezegun requests
          fi
          python -m pip install pytest pytest-cov httpx freezegun requests

      - name: Run focused Mahnwesen tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -e
          pytest -q \
            tests/agents_mahnwesen/test_morning_operate.py \
            tests/agents_mahnwesen/test_canary_engine.py \
            tests/agents_mahnwesen/test_canary_rollout.py \
            tests/agents_mahnwesen/test_operate_tools.py \
            tests/agents_mahnwesen/test_kpi_engine.py \
            tests/agents_mahnwesen/test_bounce_reconcile.py \
            tests/agents_mahnwesen/test_sender_security_tools.py \
            tests/agents_mahnwesen/test_flock_integration_offline.py \
            tests/agents_mahnwesen/test_mvr_dispatch_dryrun.py
