---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Python CI (Focused Mahnwesen)

on:
  push:
    paths:
      - 'agents/mahnwesen/**'
      - 'agents/einvoice/**'
      - 'agents/comm/**'
      - 'tests/agents_mahnwesen/**'
      - 'tests/einvoice/**'
      - 'tests/comm/**'
      - '.github/workflows/python.yml'
  pull_request:
    paths:
      - 'agents/mahnwesen/**'
      - 'agents/einvoice/**'
      - 'agents/comm/**'
      - 'tests/agents_mahnwesen/**'
      - 'tests/einvoice/**'
      - 'tests/comm/**'
      - '.github/workflows/python.yml'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      TZ: UTC
      PYTHONHASHSEED: '0'
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: '1'
      RUN_DB_TESTS: '0'
      TENANT_DEFAULT: '00000000-0000-0000-0000-000000000001'
      MVR_KILL_SWITCH: '1'
      MVR_RATE_LIMIT: '2'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if ! python -m pip install -r requirements-dev.txt; then
            python -m pip install pytest pytest-cov httpx freezegun requests pyyaml lxml jinja2
          fi
          python -m pip install jinja2

      - name: Run focused Mahnwesen & E-Invoice tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -e
          pytest -q tests/agents_mahnwesen tests/einvoice tests/comm
