---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Python CI (Guarded)
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect Python project & tests
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          has_proj=false
          has_tests=false

          # Projektindikatoren
          if [ -f "pyproject.toml" ] || [ -f "requirements.txt" ]; then
            has_proj=true
          fi

          # Testindikatoren (Dateien/Ordner)
          if [ -f "pytest.ini" ] || [ -d "tests" ]; then
            has_tests=true
          else
            # Optional: Konfigs durchsuchen (nur wenn vorhanden)
            if [ -f "pyproject.toml" ]; then
              if grep -qE '^\s*\[tool\.pytest' pyproject.toml; then
                has_tests=true
              fi
            fi
            if [ "$has_tests" = false ] && [ -f "setup.cfg" ]; then
              if grep -qi 'pytest' setup.cfg; then
                has_tests=true
              fi
            fi
          fi

          if [ "$has_proj" = true ] && [ "$has_tests" = true ]; then
            echo "run_tests=true" >> "$GITHUB_OUTPUT"
            echo "Detected Python project with tests."
          else
            echo "run_tests=false" >> "$GITHUB_OUTPUT"
            echo "No runnable Python tests detected. Exiting gracefully."
          fi

      - name: Setup Python
        if: ${{ steps.detect.outputs.run_tests == 'true' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - "name": "Install dependencies (constraints: wrapt>=1.16.0)"
        if: ${{ steps.detect.outputs.run_tests == 'true' }}
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          # temporäres Constraints-File gegen alte wrapt-Versionen (Py3.12-kompatibel)
          echo 'wrapt>=1.16.0' > /tmp/constraints-ci.txt
          if [ -f "requirements.txt" ]; then
            pip install -c /tmp/constraints-ci.txt -r requirements.txt
          fi
          # Projekt NICHT installieren (kein 'pip install .'); wir testen mit PYTHONPATH=.

      - name: Run tests
        if: ${{ steps.detect.outputs.run_tests == 'true' }}
        shell: bash
        env:
          PYTHONPATH: .
        run: |
          set -e
          pytest -q --maxfail=1

      - name: No tests – placeholder success
        if: ${{ steps.detect.outputs.run_tests != 'true' }}
        run: echo "No Python tests detected → CI success (guarded)."
